# Generated by Django 3.1.7 on 2021-03-30 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Quizz', max_length=255, verbose_name='Quizz Title')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('cateogry', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='quizz.category')),
            ],
            options={
                'verbose_name': 'Quizz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateField(auto_now_add=True, verbose_name='Last Updated')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('question_type', models.IntegerField(choices=[(0, 'Multiple Choices')], verbose_name='Type of question')),
                ('difficulty', models.IntegerField(choices=[(0, 'Fundamental'), (1, 'Beginner'), (2, 'Intermidiate'), (3, 'Advanced'), (4, 'Expert')], verbose_name='Question Difficulty')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Date Created')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active status')),
                ('quizz', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizz.quizz')),
            ],
            options={
                'verbose_name': 'Questions',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateField(auto_now_add=True, verbose_name='Last Updated')),
                ('awnser', models.CharField(max_length=250, verbose_name='Awnser Text')),
                ('is_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quizz.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Awnsers',
                'ordering': ['id'],
            },
        ),
    ]
