# Generated by Django 3.1.7 on 2021-03-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['id'], 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='awnser',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(default='Null', max_length=250, verbose_name='Answer Text'),
            preserve_default=False,
        ),
    ]
